title: Yang的后花园
subtitle: 爱美工的程序员
meta: 
  description: Yang的后花园，爱美工的程序员，zhangxiaoyang
  keywords: 学习，思考，想法
  author: zhangxiaoyang
profile:
  avatar: https://avatars3.githubusercontent.com/u/2735163?v=3&s=460
  disqus: zhangxiaoyang-me
navigation:
  - name: Home
    link: /index.html
    icon: fa-home
    color: 3369e8
  - name: Category
    link: /category.html
    icon: fa-th-large
    color: 3369e8
  - name: About
    link: /about.html
    icon: fa-user
    color: 3369e8
  - name: RSS
    link: /rss.xml
    icon: fa-rss
    color: 3369e8
site:
  url: zhangxiaoyang.me
  theme: default
  banner: http://ww3.sinaimg.cn/large/005X3nNxjw1epeyfkp54aj30sg0fr0tj.jpg
  copyright: © 2017 zhangxiaoyang.me
